name: Publish Unity3d Package
on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: 'The tag of the release to download the file from'
        required: true
      file-name:
        type: string
        description: 'The name of the file to download within the release tag'
        required: true
        

jobs:
  PublishUnity3dPackage:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.4

      - name: Apply the package from GitHub Release
        run: |
          # Clear the contents of the repository
          find . -mindepth 1 -maxdepth 1 ! -name ".git" ! -name ".github" -exec rm -rf {} +
          
          # Download the release
          ENCODED_TAG=$(jq -rn --arg v "${{ github.event.inputs.release-tag }}" '$v|@uri')
          ENCODED_NAME=$(jq -rn --arg v "${{ github.event.inputs.file-name }}" '$v|@uri')
          PACKAGE_URL=$(echo "https://github.com/PereViader/ManualDi/releases/download/$ENCODED_TAG/$ENCODED_NAME")
          echo "Downloading package at $PACKAGE_URL"
          curl -L -o "${{ github.event.inputs.file-name }}" "$PACKAGE_URL"
          
          # Extract the contents of the package into the root of the repo
          tar -xzvf "${{ github.event.inputs.file-name }}"
          mv package/* .
          rm -rf package
          rm "${{ github.event.inputs.file-name }}"

          # Upload contents to the repository
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update to ${{ github.event.inputs.release-tag }}"
          git push
          