name: Publish Unity3d Package
on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: 'The tag of the release to download the file from'
        required: true
      sync-file-name:
        type: string
        description: 'The name of the sync file to download within the release tag'
        required: true
      async-file-name:
        type: string
        description: 'The name of the async file to download within the release tag'
        required: true
        

jobs:
  PublishUnity3dPackage:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.4

      - name: Apply the package from GitHub Release
        run: |
          # Clear the contents of the repository
          find . -mindepth 1 -maxdepth 1 ! -name ".git" ! -name ".github" -exec rm -rf {} +
          
          # Download the release
          ENCODED_TAG=$(jq -rn --arg v "${{ github.event.inputs.release-tag }}" '$v|@uri')
          
          SYNC_ENCODED_NAME=$(jq -rn --arg v "${{ github.event.inputs.sync-file-name }}" '$v|@uri')
          ASYNC_ENCODED_NAME=$(jq -rn --arg v "${{ github.event.inputs.async-file-name }}" '$v|@uri')
          
          SYNC_PACKAGE_URL=$(echo "https://github.com/PereViader/ManualDi/releases/download/$ENCODED_TAG/$SYNC_ENCODED_NAME")
          ASYNC_PACKAGE_URL=$(echo "https://github.com/PereViader/ManualDi/releases/download/$ENCODED_TAG/$ASYNC_ENCODED_NAME")

          echo "Downloading package at $SYNC_PACKAGE_URL"
          curl -L -o "${{ github.event.inputs.sync-file-name }}" "$SYNC_PACKAGE_URL"
          
          echo "Downloading package at $ASYNC_PACKAGE_URL"
          curl -L -o "${{ github.event.inputs.async-file-name }}" "$ASYNC_PACKAGE_URL"

          echo "Extract the contents of the sync package"
          mkdir ManualDi.Sync.Unity3d
          tar -xzvf "${{ github.event.inputs.sync-file-name }}"
          mv package/* ManualDi.Sync.Unity3d
          rm -rf package
          rm "${{ github.event.inputs.sync-file-name }}"

          echo "Extract the contents of the async package"
          mkdir ManualDi.Async.Unity3d
          tar -xzvf "${{ github.event.inputs.async-file-name }}"
          mv package/* ManualDi.Async.Unity3d
          rm -rf package
          rm "${{ github.event.inputs.async-file-name }}"

          # Upload contents to the repository
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update to ${{ github.event.inputs.release-tag }}"
          git tag -a ${{ github.event.inputs.release-tag }} -m "Update to ${{ github.event.inputs.release-tag }}"
          git push --tags
          
